### ISSUE TITLE
General To-Do's

### ISSUE THREAD

**Issue by rohinsood** [Team-Optix-3749/Team-3749-2023#1]
- [x] Getter classes for [Limelight](https://github.com/MillenniumFalcons/2022-RapidReact-Ewok/blob/main/src/main/java/team3647/lib/vision/Limelight.java)/[PhotonVisionCamera](https://github.com/MillenniumFalcons/2022-RapidReact-Ewok/blob/main/src/main/java/team3647/lib/vision/PhotonVisionCamera.java)
 - [x] [Redundant button bindings](https://github.com/Mechanical-Advantage/RobotCode2022/blob/8195fdbd4e2cfe4a95044c186e88d970817f186c/src/main/java/frc/robot/oi/OISelector.java#L29)
 - [x] Auto selection with SmartData
